version: '3.1'

services:
  books:
    build:
      context: ./books
      dockerfile: Dockerfile
    restart: always
    container_name: books
    ports:
      - "4545:4545"
    depends_on:
      - mongo
    volumes:
      - :/app
      - /app/books/node_modules
  
  customers:
    build:
      context: ./customers
      dockerfile: Dockerfile
    restart: always
    container_name: customers
    ports:
      - "5555:5555"
    depends_on:
      - mongo
    volumes:
      - :/app
      - /app/customers/node_modules

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    restart: always
    container_name: orders
    ports:
      - "7777:7777"
    depends_on:
      - mongo
    volumes:
      - :/app
      - /app/orders/node_modules

  nginx-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - books
      - customers
      - orders
    ports:
      - "80:80"
    