version: '3.8'

services:
  books:
    build:
      context: ./books
      dockerfile: Dockerfile
    container_name: books
    ports:
      - "4545:4545"
  
  customers:
    build:
      context: ./customers
      dockerfile: Dockerfile
    restart: always
    container_name: customers
    ports:
      - "5555:5555"

  orders:
    build:
      context: ./orders
      dockerfile: Dockerfile
    restart: always
    container_name: orders
    ports:
      - "7777:7777"


  # nginx-proxy:
  #   build:
  #     context: ./proxy
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - books
  #     - customers
  #     - orders
  #   ports:
  #     - "80:80"


# ---
# version: '3.8'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: production
#       NEXT_TELEMETRY_DISABLED: 1
    